language: java
sudo: false

cache:
 directories:
  - "$HOME/.m2"

before_cache:
 - rm -rf $HOME/.m2/repository/com/github/wcosmedlr/balance-backend/

before_install:
 - chmod +x mvnw 
 - cd backend

jdk:
 - oraclejdk11
