micronaut:
  application:
    name: balance
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
jackson:
  serialization:
    writeDatesAsTimestamps: false
datasources:
  default:
    url: jdbc:mysql://${DB-HOST}:3306/balance-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: balance-us
    password: balance-pw
    schema-generate: CREATE_DROP
jpa:
  default:
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Madrid
        hbm2ddl:
          auto: update
